package excepciones.ej2;

import java.util.Scanner;

public class ExcepcionesEj2 {

    public static void main(String[] args) {
        // EJERCICIO 2
//        try {
//            String[] lista = new String[3];
//            lista[3] = "hola";
//        } catch (ArrayIndexOutOfBoundsException e) {
//            System.out.println("Se capturó una excepción de tipo fuera de índice");
//        } catch (Exception a) {
//            System.out.println("Ha ocurrido un error en general");
//        }

        // EJERCICIO 3
//        Scanner read = new Scanner(System.in).useDelimiter("\n");
//        try {
//            System.out.print("Ingrese el primer número: ");
//            String string1 = read.next();
//            System.out.print("Ingrese el segundo número: ");
//            String string2 = read.next();
//
//            int numero1 = Integer.parseInt(string1);
//            int numero2 = Integer.parseInt(string2);
//
//            double division = numero1 / numero2;
//            System.out.println("La división entre el primer número y el segundo es: " + division);
//        } catch (NumberFormatException e) {
//            System.out.println("No se ha ingresado un número. El programa se finalizará.");
//        } catch (ArithmeticException a) {
//            System.out.println("El segundo número ingresado es 0, entonces no se puede realizar la división.");
//        } finally {
//            System.out.println("Esto se va a imprimir de todas formas.");
//        }

    }

}
